-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "POLICY" NVARCHAR(10), "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" NVARCHAR(10));
CREATE TYPE "T_PREDICT" AS TABLE ("ID" INTEGER, "FRAUD" VARCHAR(1000), "SCORE" DOUBLE);
TRUNCATE TABLE "SIGNATURE";
INSERT INTO "SIGNATURE" VALUES (1, 'PALUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'PALUSER', 'T_STATE', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'PALUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'PALUSER', 'T_PREDICT', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'PREDICT_WITH_PAL_MODEL_STATE', 'PALUSER', 'P_PWMS', "SIGNATURE");

-- table setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
CREATE COLUMN TABLE "PREDICT" LIKE "T_PREDICT";

-- input data
INSERT INTO "DATA" VALUES (1, 'Travel', 56, 350, 'IT');
INSERT INTO "DATA" VALUES (2, 'Vehicle', 26, 6230, 'Marketing');
INSERT INTO "DATA" VALUES (3, 'Home', 55, 2300, 'Marketing');
INSERT INTO "DATA" VALUES (4, 'Vehicle', 31, 2134, 'Marketing');
INSERT INTO "DATA" VALUES (5, 'Vehicle', 64, 1200, 'Sales');

-- parameters

-- call : results in table
TRUNCATE TABLE "PREDICT";
CALL "P_PWMS" ("DATA", "STATE", "#PARAMS", "PREDICT") WITH OVERVIEW;
SELECT d.*, p."FRAUD", "SCORE" FROM "DATA" d INNER JOIN "PREDICT" p ON (p."ID"=d."ID");
SELECT * FROM "SYS"."M_AFL_STATES";
SELECT * FROM "SYS"."M_AFL_FUNCTIONS";
