-- parameters
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
INSERT INTO "#PARAMS" VALUES ('ALGORITHM', 1, null, null); -- 1: C45, 2: CHAID, 3: CART
INSERT INTO "#PARAMS" VALUES ('HAS_ID', 1, null, null); -- 0: no ID column, 1: first column is ID
INSERT INTO "#PARAMS" VALUES ('THREAD_RATIO', null, 1.0, null); -- Between 0 and 1

-- call : results inline
--CALL "_SYS_AFL"."PAL_DECISION_TREE" ("CLAIMS", "#PARAMS", ?, ?, ?, ?, ?);

-- call : results in tables
CREATE COLUMN TABLE "MODEL" ("ROW_INDEX" INTEGER, "MODEL_CONTENT" NVARCHAR(5000));
CREATE COLUMN TABLE "DECISION_RULES" ("ROW_INDEX" INTEGER, "RULES_CONTENT" NVARCHAR(5000));
CREATE COLUMN TABLE "CONFUSION_MATRIX" ("ACTUAL_CLASS" NVARCHAR(1000), "PREDICTED_CLASS" NVARCHAR(1000),"COUNT" INTEGER);
CREATE COLUMN TABLE "STATISTICS" ("STAT_NAME" NVARCHAR(1000), "STAT_VALUE" NVARCHAR(1000));
CREATE COLUMN TABLE "PLACEHOLDER" ("PARAM_NAME" NVARCHAR(256), "INT_VALUE" INTEGER, "DOUBLE_VALUE" DOUBLE, "STRING_VALUE" NVARCHAR(1000));
CALL "_SYS_AFL"."PAL_DECISION_TREE" ("CLAIMS", "#PARAMS", "MODEL", "DECISION_RULES", "CONFUSION_MATRIX", "STATISTICS", "PLACEHOLDER") WITH OVERVIEW;
SELECT * FROM "MODEL";
SELECT * FROM "DECISION_RULES";
SELECT * FROM "CONFUSION_MATRIX";
SELECT * FROM "STATISTICS";
SELECT * FROM "PLACEHOLDER";
