-- input data
CREATE COLUMN TABLE "CLAIMS" ("ID" INTEGER, "POLICY" NVARCHAR(10), "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" NVARCHAR(10), "ISFRAUD" NVARCHAR(10));
INSERT INTO "CLAIMS" VALUES (1,'Home',24,300,'Sales','No');
INSERT INTO "CLAIMS" VALUES (2,'Home',41,1200,'IT','No');
INSERT INTO "CLAIMS" VALUES (3,'Home',38,2800,'Sales','Yes');
INSERT INTO "CLAIMS" VALUES (4,'Home',62,6000,'Marketing','No');
INSERT INTO "CLAIMS" VALUES (5,'Home',51,4000,'Sales','No');
INSERT INTO "CLAIMS" VALUES (6,'Travel',33,200,'Sales','No');
INSERT INTO "CLAIMS" VALUES (7,'Travel',46,800,'IT','No');
INSERT INTO "CLAIMS" VALUES (8,'Travel',42,1000,'Marketing','No');
INSERT INTO "CLAIMS" VALUES (9,'Travel',21,900,'Sales','No');
INSERT INTO "CLAIMS" VALUES (10,'Vehicle',44,4000,'IT','No');
INSERT INTO "CLAIMS" VALUES (11,'Vehicle',64,1000,'Sales','Yes');
INSERT INTO "CLAIMS" VALUES (12,'Vehicle',54,900,'IT','No');
INSERT INTO "CLAIMS" VALUES (13,'Vehicle',26,2500,'Sales','No');
INSERT INTO "CLAIMS" VALUES (14,'Vehicle',44,1300,'Marketing','Yes');

-- parameters
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
INSERT INTO "#PARAMS" VALUES ('THREAD_RATIO', null, 1.0, null); -- Between 0 and 1
INSERT INTO "#PARAMS" VALUES ('HAS_ID', 1, null, null); -- 0: no ID column, 1: first column is ID
--INSERT INTO "#PARAMS" VALUES ('CATEGORICAL_VARIABLE', 3, null, null); -- specify integer column # as categorical (default for integer columns is continuous)
--INSERT INTO "#PARAMS" VALUES ('SIGNIFICANCE_LEVEL', null, 0.05, null); -- 0 --> 1
--INSERT INTO "#PARAMS" VALUES ('TRIMMED_PERCENTAGE', null, 0.05, null); -- 0 --> 0.5

-- call : results inline
--CALL "_SYS_AFL"."PAL_UNIVARIATE_ANALYSIS" ("CLAIMS", "#PARAMS", ?, ?);

-- call : results in table
CREATE COLUMN TABLE "CONTINUOUS" ("VARIABLE" NVARCHAR(256), "STATISTIC" NVARCHAR(100), "VALUE" DOUBLE);
CREATE COLUMN TABLE "CATEGORICAL" ("VARIABLE" NVARCHAR(256), "CATEGORY" NVARCHAR(256), "STATISTIC" NVARCHAR(100), "VALUE" DOUBLE);
CALL "_SYS_AFL"."PAL_UNIVARIATE_ANALYSIS" ("CLAIMS", "#PARAMS", "CONTINUOUS", "CATEGORICAL") WITH OVERVIEW;
SELECT * FROM "CONTINUOUS";
SELECT * FROM "CATEGORICAL";
